FROM pizzafactory0contorno/piatto-quadrato:debian-10.1_xpra

USER root
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
      build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 \
      libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev \
      libminiupnpc-dev \
      libzmq3-dev \
      libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools \
      libqrencode-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
USER user
